// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: case.sql

package sqlitedb

import (
	"context"
)

const getLeakageCase = `-- name: GetLeakageCase :one
SELECT
    id,
    tenant_id,
    customer_id,
    contract_id,
    case_type,
    severity,
    status,
    detected_at,
    period_start,
    period_end,
    expected_amount_minor_units,
    actual_amount_minor_units,
    leakage_amount_minor_units,
    currency,
    confidence_score_basis_points,
    root_cause_category,
    assignee,
    trace_id
FROM leakage_cases
WHERE tenant_id = ?1
  AND id = ?2
`

type GetLeakageCaseParams struct {
	TenantID string `json:"tenant_id"`
	CaseID   string `json:"case_id"`
}

func (q *Queries) GetLeakageCase(ctx context.Context, arg GetLeakageCaseParams) (LeakageCase, error) {
	row := q.db.QueryRowContext(ctx, getLeakageCase, arg.TenantID, arg.CaseID)
	var i LeakageCase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ContractID,
		&i.CaseType,
		&i.Severity,
		&i.Status,
		&i.DetectedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.ExpectedAmountMinorUnits,
		&i.ActualAmountMinorUnits,
		&i.LeakageAmountMinorUnits,
		&i.Currency,
		&i.ConfidenceScoreBasisPoints,
		&i.RootCauseCategory,
		&i.Assignee,
		&i.TraceID,
	)
	return i, err
}

const listLeakageCases = `-- name: ListLeakageCases :many
SELECT
    id,
    tenant_id,
    customer_id,
    contract_id,
    case_type,
    severity,
    status,
    detected_at,
    period_start,
    period_end,
    expected_amount_minor_units,
    actual_amount_minor_units,
    leakage_amount_minor_units,
    currency,
    confidence_score_basis_points,
    root_cause_category,
    assignee,
    trace_id
FROM leakage_cases
WHERE tenant_id = ?1
  AND (?2 IS NULL OR contract_id = ?2)
  AND (?3 IS NULL OR status = ?3)
ORDER BY detected_at DESC, id DESC
LIMIT ?5
OFFSET ?4
`

type ListLeakageCasesParams struct {
	TenantID    string      `json:"tenant_id"`
	ContractID  interface{} `json:"contract_id"`
	Status      interface{} `json:"status"`
	OffsetCount int64       `json:"offset_count"`
	LimitCount  int64       `json:"limit_count"`
}

func (q *Queries) ListLeakageCases(ctx context.Context, arg ListLeakageCasesParams) ([]LeakageCase, error) {
	rows, err := q.db.QueryContext(ctx, listLeakageCases,
		arg.TenantID,
		arg.ContractID,
		arg.Status,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeakageCase{}
	for rows.Next() {
		var i LeakageCase
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ContractID,
			&i.CaseType,
			&i.Severity,
			&i.Status,
			&i.DetectedAt,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.ExpectedAmountMinorUnits,
			&i.ActualAmountMinorUnits,
			&i.LeakageAmountMinorUnits,
			&i.Currency,
			&i.ConfidenceScoreBasisPoints,
			&i.RootCauseCategory,
			&i.Assignee,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeakageEvidenceByCase = `-- name: ListLeakageEvidenceByCase :many
SELECT
    id,
    case_id,
    evidence_type,
    entity_type,
    entity_id,
    payload_json,
    created_at
FROM leakage_evidence
WHERE case_id = ?1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListLeakageEvidenceByCase(ctx context.Context, caseID string) ([]LeakageEvidence, error) {
	rows, err := q.db.QueryContext(ctx, listLeakageEvidenceByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeakageEvidence{}
	for rows.Next() {
		var i LeakageEvidence
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.EvidenceType,
			&i.EntityType,
			&i.EntityID,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCausesByCase = `-- name: ListRootCausesByCase :many
SELECT
    id,
    case_id,
    category,
    subcategory,
    description,
    confidence_score_basis_points,
    derived_by,
    created_at
FROM root_causes
WHERE case_id = ?1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListRootCausesByCase(ctx context.Context, caseID string) ([]RootCause, error) {
	rows, err := q.db.QueryContext(ctx, listRootCausesByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RootCause{}
	for rows.Next() {
		var i RootCause
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Category,
			&i.Subcategory,
			&i.Description,
			&i.ConfidenceScoreBasisPoints,
			&i.DerivedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
