// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: case.sql

package sqlitedb

import (
	"context"
)

const createCaseStatusHistory = `-- name: CreateCaseStatusHistory :exec
INSERT INTO case_status_history (
    id,
    case_id,
    from_status,
    to_status,
    changed_at,
    changed_by,
    reason_code,
    comment
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type CreateCaseStatusHistoryParams struct {
	ID         string `json:"id"`
	CaseID     string `json:"case_id"`
	FromStatus string `json:"from_status"`
	ToStatus   string `json:"to_status"`
	ChangedAt  string `json:"changed_at"`
	ChangedBy  string `json:"changed_by"`
	ReasonCode string `json:"reason_code"`
	Comment    string `json:"comment"`
}

func (q *Queries) CreateCaseStatusHistory(ctx context.Context, arg CreateCaseStatusHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createCaseStatusHistory,
		arg.ID,
		arg.CaseID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedAt,
		arg.ChangedBy,
		arg.ReasonCode,
		arg.Comment,
	)
	return err
}

const getLeakageCase = `-- name: GetLeakageCase :one
SELECT
    id,
    tenant_id,
    customer_id,
    contract_id,
    reconciliation_run_id,
    case_type,
    severity,
    status,
    detected_at,
    period_start,
    period_end,
    expected_amount_minor_units,
    actual_amount_minor_units,
    leakage_amount_minor_units,
    currency,
    confidence_score_basis_points,
    root_cause_category,
    assignee,
    trace_id
FROM leakage_cases
WHERE tenant_id = ?1
  AND id = ?2
`

type GetLeakageCaseParams struct {
	TenantID string `json:"tenant_id"`
	CaseID   string `json:"case_id"`
}

func (q *Queries) GetLeakageCase(ctx context.Context, arg GetLeakageCaseParams) (LeakageCase, error) {
	row := q.db.QueryRowContext(ctx, getLeakageCase, arg.TenantID, arg.CaseID)
	var i LeakageCase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ContractID,
		&i.ReconciliationRunID,
		&i.CaseType,
		&i.Severity,
		&i.Status,
		&i.DetectedAt,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.ExpectedAmountMinorUnits,
		&i.ActualAmountMinorUnits,
		&i.LeakageAmountMinorUnits,
		&i.Currency,
		&i.ConfidenceScoreBasisPoints,
		&i.RootCauseCategory,
		&i.Assignee,
		&i.TraceID,
	)
	return i, err
}

const listCaseStatusHistoryByCase = `-- name: ListCaseStatusHistoryByCase :many
SELECT
    id,
    case_id,
    from_status,
    to_status,
    changed_at,
    changed_by,
    reason_code,
    comment
FROM case_status_history
WHERE case_id = ?1
ORDER BY changed_at ASC, id ASC
`

func (q *Queries) ListCaseStatusHistoryByCase(ctx context.Context, caseID string) ([]CaseStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listCaseStatusHistoryByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseStatusHistory{}
	for rows.Next() {
		var i CaseStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedAt,
			&i.ChangedBy,
			&i.ReasonCode,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeakageCases = `-- name: ListLeakageCases :many
SELECT
    id,
    tenant_id,
    customer_id,
    contract_id,
    reconciliation_run_id,
    case_type,
    severity,
    status,
    detected_at,
    period_start,
    period_end,
    expected_amount_minor_units,
    actual_amount_minor_units,
    leakage_amount_minor_units,
    currency,
    confidence_score_basis_points,
    root_cause_category,
    assignee,
    trace_id
FROM leakage_cases
WHERE tenant_id = ?1
  AND (?2 IS NULL OR contract_id = ?2)
  AND (?3 IS NULL OR status = ?3)
  AND (?4 IS NULL OR severity = ?4)
  AND (?5 IS NULL OR detected_at >= ?5)
  AND (?6 IS NULL OR detected_at < ?6)
  AND (
    ?7 IS NULL
    OR id LIKE '%' || ?7 || '%'
    OR contract_id LIKE '%' || ?7 || '%'
    OR root_cause_category LIKE '%' || ?7 || '%'
    OR assignee LIKE '%' || ?7 || '%'
    OR trace_id LIKE '%' || ?7 || '%'
  )
ORDER BY detected_at DESC, id DESC
LIMIT ?9
OFFSET ?8
`

type ListLeakageCasesParams struct {
	TenantID     string      `json:"tenant_id"`
	ContractID   interface{} `json:"contract_id"`
	Status       interface{} `json:"status"`
	Severity     interface{} `json:"severity"`
	DetectedFrom interface{} `json:"detected_from"`
	DetectedTo   interface{} `json:"detected_to"`
	SearchQuery  interface{} `json:"search_query"`
	OffsetCount  int64       `json:"offset_count"`
	LimitCount   int64       `json:"limit_count"`
}

func (q *Queries) ListLeakageCases(ctx context.Context, arg ListLeakageCasesParams) ([]LeakageCase, error) {
	rows, err := q.db.QueryContext(ctx, listLeakageCases,
		arg.TenantID,
		arg.ContractID,
		arg.Status,
		arg.Severity,
		arg.DetectedFrom,
		arg.DetectedTo,
		arg.SearchQuery,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeakageCase{}
	for rows.Next() {
		var i LeakageCase
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ContractID,
			&i.ReconciliationRunID,
			&i.CaseType,
			&i.Severity,
			&i.Status,
			&i.DetectedAt,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.ExpectedAmountMinorUnits,
			&i.ActualAmountMinorUnits,
			&i.LeakageAmountMinorUnits,
			&i.Currency,
			&i.ConfidenceScoreBasisPoints,
			&i.RootCauseCategory,
			&i.Assignee,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeakageEvidenceByCase = `-- name: ListLeakageEvidenceByCase :many
SELECT
    id,
    case_id,
    evidence_type,
    entity_type,
    entity_id,
    payload_json,
    created_at
FROM leakage_evidence
WHERE case_id = ?1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListLeakageEvidenceByCase(ctx context.Context, caseID string) ([]LeakageEvidence, error) {
	rows, err := q.db.QueryContext(ctx, listLeakageEvidenceByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeakageEvidence{}
	for rows.Next() {
		var i LeakageEvidence
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.EvidenceType,
			&i.EntityType,
			&i.EntityID,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCausesByCase = `-- name: ListRootCausesByCase :many
SELECT
    id,
    case_id,
    category,
    subcategory,
    description,
    confidence_score_basis_points,
    derived_by,
    created_at
FROM root_causes
WHERE case_id = ?1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListRootCausesByCase(ctx context.Context, caseID string) ([]RootCause, error) {
	rows, err := q.db.QueryContext(ctx, listRootCausesByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RootCause{}
	for rows.Next() {
		var i RootCause
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Category,
			&i.Subcategory,
			&i.Description,
			&i.ConfidenceScoreBasisPoints,
			&i.DerivedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeakageCaseAssignee = `-- name: UpdateLeakageCaseAssignee :execrows
UPDATE leakage_cases
SET assignee = ?1
WHERE tenant_id = ?2
  AND id = ?3
`

type UpdateLeakageCaseAssigneeParams struct {
	Assignee string `json:"assignee"`
	TenantID string `json:"tenant_id"`
	CaseID   string `json:"case_id"`
}

func (q *Queries) UpdateLeakageCaseAssignee(ctx context.Context, arg UpdateLeakageCaseAssigneeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLeakageCaseAssignee, arg.Assignee, arg.TenantID, arg.CaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLeakageCaseStatus = `-- name: UpdateLeakageCaseStatus :execrows
UPDATE leakage_cases
SET status = ?1
WHERE tenant_id = ?2
  AND id = ?3
`

type UpdateLeakageCaseStatusParams struct {
	Status   string `json:"status"`
	TenantID string `json:"tenant_id"`
	CaseID   string `json:"case_id"`
}

func (q *Queries) UpdateLeakageCaseStatus(ctx context.Context, arg UpdateLeakageCaseStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLeakageCaseStatus, arg.Status, arg.TenantID, arg.CaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
