// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contract.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const getBillableItem = `-- name: GetBillableItem :one
SELECT
  id, tenant_id, code, name, category, unit, pricing_mode, status, created_at
FROM
  billable_items
WHERE
  id = ?
LIMIT
  1
`

func (q *Queries) GetBillableItem(ctx context.Context, id string) (BillableItem, error) {
	row := q.db.QueryRowContext(ctx, getBillableItem, id)
	var i BillableItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.PricingMode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getBillableItemByCode = `-- name: GetBillableItemByCode :one
SELECT
  id, tenant_id, code, name, category, unit, pricing_mode, status, created_at
FROM
  billable_items
WHERE
  tenant_id = ?
  AND code = ?
LIMIT
  1
`

type GetBillableItemByCodeParams struct {
	TenantID string `json:"tenant_id"`
	Code     string `json:"code"`
}

func (q *Queries) GetBillableItemByCode(ctx context.Context, arg GetBillableItemByCodeParams) (BillableItem, error) {
	row := q.db.QueryRowContext(ctx, getBillableItemByCode, arg.TenantID, arg.Code)
	var i BillableItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.PricingMode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getContract = `-- name: GetContract :one
SELECT
  id, tenant_id, customer_id, external_id, status, start_date, end_date, currency, version, billing_model, signed_at, metadata_json, created_at, updated_at
FROM
  contracts
WHERE
  id = ?
LIMIT
  1
`

func (q *Queries) GetContract(ctx context.Context, id string) (Contract, error) {
	row := q.db.QueryRowContext(ctx, getContract, id)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ExternalID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Currency,
		&i.Version,
		&i.BillingModel,
		&i.SignedAt,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBillableItems = `-- name: ListBillableItems :many
SELECT
  id, tenant_id, code, name, category, unit, pricing_mode, status, created_at
FROM
  billable_items
WHERE
  tenant_id = ?
ORDER BY
  code
`

func (q *Queries) ListBillableItems(ctx context.Context, tenantID string) ([]BillableItem, error) {
	rows, err := q.db.QueryContext(ctx, listBillableItems, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillableItem{}
	for rows.Next() {
		var i BillableItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Category,
			&i.Unit,
			&i.PricingMode,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractTerms = `-- name: ListContractTerms :many
SELECT
  id, tenant_id, contract_id, term_type, effective_from, effective_to, priority, expression_json, source_ref, created_at
FROM
  contract_terms
WHERE
  contract_id = ?
ORDER BY
  priority DESC,
  created_at DESC
`

func (q *Queries) ListContractTerms(ctx context.Context, contractID string) ([]ContractTerm, error) {
	rows, err := q.db.QueryContext(ctx, listContractTerms, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractTerm{}
	for rows.Next() {
		var i ContractTerm
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContractID,
			&i.TermType,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Priority,
			&i.ExpressionJson,
			&i.SourceRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractsByCustomer = `-- name: ListContractsByCustomer :many
SELECT
  id, tenant_id, customer_id, external_id, status, start_date, end_date, currency, version, billing_model, signed_at, metadata_json, created_at, updated_at
FROM
  contracts
WHERE
  tenant_id = ?
  AND customer_id = ?
ORDER BY
  created_at DESC
`

type ListContractsByCustomerParams struct {
	TenantID   string `json:"tenant_id"`
	CustomerID string `json:"customer_id"`
}

func (q *Queries) ListContractsByCustomer(ctx context.Context, arg ListContractsByCustomerParams) ([]Contract, error) {
	rows, err := q.db.QueryContext(ctx, listContractsByCustomer, arg.TenantID, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contract{}
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ExternalID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.Currency,
			&i.Version,
			&i.BillingModel,
			&i.SignedAt,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectiveContractTerms = `-- name: ListEffectiveContractTerms :many
SELECT
  id, tenant_id, contract_id, term_type, effective_from, effective_to, priority, expression_json, source_ref, created_at
FROM
  contract_terms
WHERE
  contract_id = ?
  AND effective_from <= ?
  AND (
    effective_to IS NULL
    OR effective_to >= ?
  )
ORDER BY
  priority DESC,
  created_at DESC
`

type ListEffectiveContractTermsParams struct {
	ContractID    string         `json:"contract_id"`
	EffectiveFrom string         `json:"effective_from"`
	EffectiveTo   sql.NullString `json:"effective_to"`
}

func (q *Queries) ListEffectiveContractTerms(ctx context.Context, arg ListEffectiveContractTermsParams) ([]ContractTerm, error) {
	rows, err := q.db.QueryContext(ctx, listEffectiveContractTerms, arg.ContractID, arg.EffectiveFrom, arg.EffectiveTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractTerm{}
	for rows.Next() {
		var i ContractTerm
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContractID,
			&i.TermType,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Priority,
			&i.ExpressionJson,
			&i.SourceRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBillableItem = `-- name: UpsertBillableItem :exec
INSERT INTO
  billable_items (
    id,
    tenant_id,
    code,
    name,
    category,
    unit,
    pricing_mode,
    status,
    created_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE
SET
  name = excluded.name,
  category = excluded.category,
  unit = excluded.unit,
  pricing_mode = excluded.pricing_mode,
  status = excluded.status
`

type UpsertBillableItemParams struct {
	ID          string `json:"id"`
	TenantID    string `json:"tenant_id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	Unit        string `json:"unit"`
	PricingMode string `json:"pricing_mode"`
	Status      string `json:"status"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) UpsertBillableItem(ctx context.Context, arg UpsertBillableItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertBillableItem,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Category,
		arg.Unit,
		arg.PricingMode,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const upsertContract = `-- name: UpsertContract :exec
INSERT INTO
  contracts (
    id,
    tenant_id,
    customer_id,
    external_id,
    status,
    start_date,
    end_date,
    currency,
    version,
    billing_model,
    signed_at,
    metadata_json,
    created_at,
    updated_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE
SET
  status = excluded.status,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  version = excluded.version,
  billing_model = excluded.billing_model,
  signed_at = excluded.signed_at,
  metadata_json = excluded.metadata_json,
  updated_at = excluded.updated_at
`

type UpsertContractParams struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	CustomerID   string         `json:"customer_id"`
	ExternalID   sql.NullString `json:"external_id"`
	Status       string         `json:"status"`
	StartDate    string         `json:"start_date"`
	EndDate      sql.NullString `json:"end_date"`
	Currency     string         `json:"currency"`
	Version      int64          `json:"version"`
	BillingModel string         `json:"billing_model"`
	SignedAt     sql.NullString `json:"signed_at"`
	MetadataJson string         `json:"metadata_json"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) UpsertContract(ctx context.Context, arg UpsertContractParams) error {
	_, err := q.db.ExecContext(ctx, upsertContract,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.ExternalID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.Currency,
		arg.Version,
		arg.BillingModel,
		arg.SignedAt,
		arg.MetadataJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertContractTerm = `-- name: UpsertContractTerm :exec
INSERT INTO
  contract_terms (
    id,
    tenant_id,
    contract_id,
    term_type,
    effective_from,
    effective_to,
    priority,
    expression_json,
    source_ref,
    created_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE
SET
  term_type = excluded.term_type,
  effective_from = excluded.effective_from,
  effective_to = excluded.effective_to,
  priority = excluded.priority,
  expression_json = excluded.expression_json,
  source_ref = excluded.source_ref
`

type UpsertContractTermParams struct {
	ID             string         `json:"id"`
	TenantID       string         `json:"tenant_id"`
	ContractID     string         `json:"contract_id"`
	TermType       string         `json:"term_type"`
	EffectiveFrom  string         `json:"effective_from"`
	EffectiveTo    sql.NullString `json:"effective_to"`
	Priority       int64          `json:"priority"`
	ExpressionJson string         `json:"expression_json"`
	SourceRef      string         `json:"source_ref"`
	CreatedAt      string         `json:"created_at"`
}

func (q *Queries) UpsertContractTerm(ctx context.Context, arg UpsertContractTermParams) error {
	_, err := q.db.ExecContext(ctx, upsertContractTerm,
		arg.ID,
		arg.TenantID,
		arg.ContractID,
		arg.TermType,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.Priority,
		arg.ExpressionJson,
		arg.SourceRef,
		arg.CreatedAt,
	)
	return err
}
