// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createDocument = `-- name: CreateDocument :exec
INSERT INTO documents (
    id,
    tenant_id,
    source_type,
    file_name,
    content_type,
    size_bytes,
    sha256_hash,
    storage_key,
    status,
    uploaded_at,
    metadata_json
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
ON CONFLICT(tenant_id, sha256_hash) DO UPDATE SET
    source_type = excluded.source_type,
    file_name = excluded.file_name,
    content_type = excluded.content_type,
    size_bytes = excluded.size_bytes,
    storage_key = excluded.storage_key,
    status = excluded.status,
    uploaded_at = excluded.uploaded_at,
    metadata_json = excluded.metadata_json
`

type CreateDocumentParams struct {
	ID           string `json:"id"`
	TenantID     string `json:"tenant_id"`
	SourceType   string `json:"source_type"`
	FileName     string `json:"file_name"`
	ContentType  string `json:"content_type"`
	SizeBytes    int64  `json:"size_bytes"`
	Sha256Hash   string `json:"sha256_hash"`
	StorageKey   string `json:"storage_key"`
	Status       string `json:"status"`
	UploadedAt   string `json:"uploaded_at"`
	MetadataJson string `json:"metadata_json"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.ExecContext(ctx, createDocument,
		arg.ID,
		arg.TenantID,
		arg.SourceType,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256Hash,
		arg.StorageKey,
		arg.Status,
		arg.UploadedAt,
		arg.MetadataJson,
	)
	return err
}

const createDocumentExtractionDraft = `-- name: CreateDocumentExtractionDraft :exec
INSERT INTO document_extraction_drafts (
    id,
    document_id,
    tenant_id,
    draft_type,
    status,
    model,
    prompt_version,
    input_hash,
    output_json,
    evidence_json,
    confidence_score_basis_points,
    created_at,
    reviewed_by,
    reviewed_at,
    rejection_reason
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateDocumentExtractionDraftParams struct {
	ID                         string         `json:"id"`
	DocumentID                 string         `json:"document_id"`
	TenantID                   string         `json:"tenant_id"`
	DraftType                  string         `json:"draft_type"`
	Status                     string         `json:"status"`
	Model                      string         `json:"model"`
	PromptVersion              string         `json:"prompt_version"`
	InputHash                  string         `json:"input_hash"`
	OutputJson                 string         `json:"output_json"`
	EvidenceJson               string         `json:"evidence_json"`
	ConfidenceScoreBasisPoints int64          `json:"confidence_score_basis_points"`
	CreatedAt                  string         `json:"created_at"`
	ReviewedBy                 string         `json:"reviewed_by"`
	ReviewedAt                 sql.NullString `json:"reviewed_at"`
	RejectionReason            string         `json:"rejection_reason"`
}

func (q *Queries) CreateDocumentExtractionDraft(ctx context.Context, arg CreateDocumentExtractionDraftParams) error {
	_, err := q.db.ExecContext(ctx, createDocumentExtractionDraft,
		arg.ID,
		arg.DocumentID,
		arg.TenantID,
		arg.DraftType,
		arg.Status,
		arg.Model,
		arg.PromptVersion,
		arg.InputHash,
		arg.OutputJson,
		arg.EvidenceJson,
		arg.ConfidenceScoreBasisPoints,
		arg.CreatedAt,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.RejectionReason,
	)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, tenant_id, source_type, file_name, content_type, size_bytes, sha256_hash, storage_key, status, uploaded_at, metadata_json
FROM documents
WHERE tenant_id = ? AND id = ?
`

type GetDocumentParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, arg.TenantID, arg.ID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceType,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256Hash,
		&i.StorageKey,
		&i.Status,
		&i.UploadedAt,
		&i.MetadataJson,
	)
	return i, err
}

const getDocumentExtractionDraft = `-- name: GetDocumentExtractionDraft :one
SELECT id, document_id, tenant_id, draft_type, status, model, prompt_version, input_hash, output_json, evidence_json, confidence_score_basis_points, created_at, reviewed_by, reviewed_at, rejection_reason
FROM document_extraction_drafts
WHERE tenant_id = ? AND id = ?
`

type GetDocumentExtractionDraftParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetDocumentExtractionDraft(ctx context.Context, arg GetDocumentExtractionDraftParams) (DocumentExtractionDraft, error) {
	row := q.db.QueryRowContext(ctx, getDocumentExtractionDraft, arg.TenantID, arg.ID)
	var i DocumentExtractionDraft
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.TenantID,
		&i.DraftType,
		&i.Status,
		&i.Model,
		&i.PromptVersion,
		&i.InputHash,
		&i.OutputJson,
		&i.EvidenceJson,
		&i.ConfidenceScoreBasisPoints,
		&i.CreatedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectionReason,
	)
	return i, err
}

const listDocumentExtractionDrafts = `-- name: ListDocumentExtractionDrafts :many
SELECT id, document_id, tenant_id, draft_type, status, model, prompt_version, input_hash, output_json, evidence_json, confidence_score_basis_points, created_at, reviewed_by, reviewed_at, rejection_reason
FROM document_extraction_drafts
WHERE tenant_id = ? AND document_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListDocumentExtractionDraftsParams struct {
	TenantID   string `json:"tenant_id"`
	DocumentID string `json:"document_id"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

func (q *Queries) ListDocumentExtractionDrafts(ctx context.Context, arg ListDocumentExtractionDraftsParams) ([]DocumentExtractionDraft, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentExtractionDrafts,
		arg.TenantID,
		arg.DocumentID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentExtractionDraft{}
	for rows.Next() {
		var i DocumentExtractionDraft
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.TenantID,
			&i.DraftType,
			&i.Status,
			&i.Model,
			&i.PromptVersion,
			&i.InputHash,
			&i.OutputJson,
			&i.EvidenceJson,
			&i.ConfidenceScoreBasisPoints,
			&i.CreatedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.RejectionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, tenant_id, source_type, file_name, content_type, size_bytes, sha256_hash, storage_key, status, uploaded_at, metadata_json
FROM documents
WHERE tenant_id = ?
ORDER BY uploaded_at DESC
LIMIT ? OFFSET ?
`

type ListDocumentsParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceType,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256Hash,
			&i.StorageKey,
			&i.Status,
			&i.UploadedAt,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
