// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestion.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createInvoiceLine = `-- name: CreateInvoiceLine :exec
INSERT INTO
  invoice_lines (
    id,
    invoice_id,
    tenant_id,
    billable_item_id,
    description,
    quantity,
    unit_price_minor_units,
    discount_amount_minor_units,
    tax_amount_minor_units,
    line_total_minor_units,
    currency,
    source_ref,
    pricing_snapshot_json,
    created_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateInvoiceLineParams struct {
	ID                       string         `json:"id"`
	InvoiceID                string         `json:"invoice_id"`
	TenantID                 string         `json:"tenant_id"`
	BillableItemID           sql.NullString `json:"billable_item_id"`
	Description              string         `json:"description"`
	Quantity                 int64          `json:"quantity"`
	UnitPriceMinorUnits      int64          `json:"unit_price_minor_units"`
	DiscountAmountMinorUnits int64          `json:"discount_amount_minor_units"`
	TaxAmountMinorUnits      int64          `json:"tax_amount_minor_units"`
	LineTotalMinorUnits      int64          `json:"line_total_minor_units"`
	Currency                 string         `json:"currency"`
	SourceRef                string         `json:"source_ref"`
	PricingSnapshotJson      string         `json:"pricing_snapshot_json"`
	CreatedAt                string         `json:"created_at"`
}

func (q *Queries) CreateInvoiceLine(ctx context.Context, arg CreateInvoiceLineParams) error {
	_, err := q.db.ExecContext(ctx, createInvoiceLine,
		arg.ID,
		arg.InvoiceID,
		arg.TenantID,
		arg.BillableItemID,
		arg.Description,
		arg.Quantity,
		arg.UnitPriceMinorUnits,
		arg.DiscountAmountMinorUnits,
		arg.TaxAmountMinorUnits,
		arg.LineTotalMinorUnits,
		arg.Currency,
		arg.SourceRef,
		arg.PricingSnapshotJson,
		arg.CreatedAt,
	)
	return err
}

const deleteInvoiceLinesByInvoice = `-- name: DeleteInvoiceLinesByInvoice :exec
DELETE FROM invoice_lines
WHERE
  invoice_id = ?
`

func (q *Queries) DeleteInvoiceLinesByInvoice(ctx context.Context, invoiceID string) error {
	_, err := q.db.ExecContext(ctx, deleteInvoiceLinesByInvoice, invoiceID)
	return err
}

const getInvoiceBySourceExternal = `-- name: GetInvoiceBySourceExternal :one
SELECT
  id, tenant_id, customer_id, contract_id, external_id, invoice_number, period_start, period_end, issued_at, due_at, currency, total_amount_minor_units, status, source_system, created_at
FROM
  invoices
WHERE
  tenant_id = ?
  AND source_system = ?
  AND external_id = ?
LIMIT
  1
`

type GetInvoiceBySourceExternalParams struct {
	TenantID     string `json:"tenant_id"`
	SourceSystem string `json:"source_system"`
	ExternalID   string `json:"external_id"`
}

func (q *Queries) GetInvoiceBySourceExternal(ctx context.Context, arg GetInvoiceBySourceExternalParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceBySourceExternal, arg.TenantID, arg.SourceSystem, arg.ExternalID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ContractID,
		&i.ExternalID,
		&i.InvoiceNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssuedAt,
		&i.DueAt,
		&i.Currency,
		&i.TotalAmountMinorUnits,
		&i.Status,
		&i.SourceSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoiceLinesByInvoice = `-- name: ListInvoiceLinesByInvoice :many
SELECT
  id, invoice_id, tenant_id, billable_item_id, description, quantity, unit_price_minor_units, discount_amount_minor_units, tax_amount_minor_units, line_total_minor_units, currency, source_ref, pricing_snapshot_json, created_at
FROM
  invoice_lines
WHERE
  invoice_id = ?
ORDER BY
  created_at ASC
`

func (q *Queries) ListInvoiceLinesByInvoice(ctx context.Context, invoiceID string) ([]InvoiceLine, error) {
	rows, err := q.db.QueryContext(ctx, listInvoiceLinesByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceLine{}
	for rows.Next() {
		var i InvoiceLine
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.TenantID,
			&i.BillableItemID,
			&i.Description,
			&i.Quantity,
			&i.UnitPriceMinorUnits,
			&i.DiscountAmountMinorUnits,
			&i.TaxAmountMinorUnits,
			&i.LineTotalMinorUnits,
			&i.Currency,
			&i.SourceRef,
			&i.PricingSnapshotJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesForContractPeriod = `-- name: ListInvoicesForContractPeriod :many
SELECT
  id, tenant_id, customer_id, contract_id, external_id, invoice_number, period_start, period_end, issued_at, due_at, currency, total_amount_minor_units, status, source_system, created_at
FROM
  invoices
WHERE
  tenant_id = ?
  AND contract_id = ?
  AND period_start = ?
  AND period_end = ?
ORDER BY
  issued_at ASC
`

type ListInvoicesForContractPeriodParams struct {
	TenantID    string `json:"tenant_id"`
	ContractID  string `json:"contract_id"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

func (q *Queries) ListInvoicesForContractPeriod(ctx context.Context, arg ListInvoicesForContractPeriodParams) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesForContractPeriod,
		arg.TenantID,
		arg.ContractID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ContractID,
			&i.ExternalID,
			&i.InvoiceNumber,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.IssuedAt,
			&i.DueAt,
			&i.Currency,
			&i.TotalAmountMinorUnits,
			&i.Status,
			&i.SourceSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageRecordsForContractPeriod = `-- name: ListUsageRecordsForContractPeriod :many
SELECT
  id, tenant_id, customer_id, contract_id, billable_item_id, external_id, usage_time, quantity, unit, source_system, trace_id, metadata_json, created_at
FROM
  usage_records
WHERE
  tenant_id = ?
  AND contract_id = ?
  AND usage_time >= ?
  AND usage_time < ?
ORDER BY
  usage_time ASC
`

type ListUsageRecordsForContractPeriodParams struct {
	TenantID    string `json:"tenant_id"`
	ContractID  string `json:"contract_id"`
	UsageTime   string `json:"usage_time"`
	UsageTime_2 string `json:"usage_time_2"`
}

func (q *Queries) ListUsageRecordsForContractPeriod(ctx context.Context, arg ListUsageRecordsForContractPeriodParams) ([]UsageRecord, error) {
	rows, err := q.db.QueryContext(ctx, listUsageRecordsForContractPeriod,
		arg.TenantID,
		arg.ContractID,
		arg.UsageTime,
		arg.UsageTime_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageRecord{}
	for rows.Next() {
		var i UsageRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ContractID,
			&i.BillableItemID,
			&i.ExternalID,
			&i.UsageTime,
			&i.Quantity,
			&i.Unit,
			&i.SourceSystem,
			&i.TraceID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInvoice = `-- name: UpsertInvoice :exec
INSERT INTO
  invoices (
    id,
    tenant_id,
    customer_id,
    contract_id,
    external_id,
    invoice_number,
    period_start,
    period_end,
    issued_at,
    due_at,
    currency,
    total_amount_minor_units,
    status,
    source_system,
    created_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (tenant_id, source_system, external_id) DO UPDATE
SET
  customer_id = excluded.customer_id,
  contract_id = excluded.contract_id,
  invoice_number = excluded.invoice_number,
  period_start = excluded.period_start,
  period_end = excluded.period_end,
  issued_at = excluded.issued_at,
  due_at = excluded.due_at,
  currency = excluded.currency,
  total_amount_minor_units = excluded.total_amount_minor_units,
  status = excluded.status
`

type UpsertInvoiceParams struct {
	ID                    string         `json:"id"`
	TenantID              string         `json:"tenant_id"`
	CustomerID            string         `json:"customer_id"`
	ContractID            string         `json:"contract_id"`
	ExternalID            string         `json:"external_id"`
	InvoiceNumber         string         `json:"invoice_number"`
	PeriodStart           string         `json:"period_start"`
	PeriodEnd             string         `json:"period_end"`
	IssuedAt              string         `json:"issued_at"`
	DueAt                 sql.NullString `json:"due_at"`
	Currency              string         `json:"currency"`
	TotalAmountMinorUnits int64          `json:"total_amount_minor_units"`
	Status                string         `json:"status"`
	SourceSystem          string         `json:"source_system"`
	CreatedAt             string         `json:"created_at"`
}

func (q *Queries) UpsertInvoice(ctx context.Context, arg UpsertInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, upsertInvoice,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.ContractID,
		arg.ExternalID,
		arg.InvoiceNumber,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.IssuedAt,
		arg.DueAt,
		arg.Currency,
		arg.TotalAmountMinorUnits,
		arg.Status,
		arg.SourceSystem,
		arg.CreatedAt,
	)
	return err
}

const upsertUsageRecord = `-- name: UpsertUsageRecord :exec
INSERT INTO
  usage_records (
    id,
    tenant_id,
    customer_id,
    contract_id,
    billable_item_id,
    external_id,
    usage_time,
    quantity,
    unit,
    source_system,
    trace_id,
    metadata_json,
    created_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (tenant_id, source_system, external_id) DO UPDATE
SET
  customer_id = excluded.customer_id,
  contract_id = excluded.contract_id,
  billable_item_id = excluded.billable_item_id,
  usage_time = excluded.usage_time,
  quantity = excluded.quantity,
  unit = excluded.unit,
  trace_id = excluded.trace_id,
  metadata_json = excluded.metadata_json
`

type UpsertUsageRecordParams struct {
	ID             string `json:"id"`
	TenantID       string `json:"tenant_id"`
	CustomerID     string `json:"customer_id"`
	ContractID     string `json:"contract_id"`
	BillableItemID string `json:"billable_item_id"`
	ExternalID     string `json:"external_id"`
	UsageTime      string `json:"usage_time"`
	Quantity       int64  `json:"quantity"`
	Unit           string `json:"unit"`
	SourceSystem   string `json:"source_system"`
	TraceID        string `json:"trace_id"`
	MetadataJson   string `json:"metadata_json"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) UpsertUsageRecord(ctx context.Context, arg UpsertUsageRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertUsageRecord,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.ContractID,
		arg.BillableItemID,
		arg.ExternalID,
		arg.UsageTime,
		arg.Quantity,
		arg.Unit,
		arg.SourceSystem,
		arg.TraceID,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	return err
}
