// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestion.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createInvoiceLine = `-- name: CreateInvoiceLine :exec
INSERT INTO
  invoice_lines (
    id,
    invoice_id,
    tenant_id,
    billable_item_id,
    description,
    quantity,
    unit_price_minor_units,
    discount_amount_minor_units,
    tax_amount_minor_units,
    line_total_minor_units,
    currency,
    source_ref,
    pricing_snapshot_json,
    created_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateInvoiceLineParams struct {
	ID                       string         `json:"id"`
	InvoiceID                string         `json:"invoice_id"`
	TenantID                 string         `json:"tenant_id"`
	BillableItemID           sql.NullString `json:"billable_item_id"`
	Description              string         `json:"description"`
	Quantity                 int64          `json:"quantity"`
	UnitPriceMinorUnits      int64          `json:"unit_price_minor_units"`
	DiscountAmountMinorUnits int64          `json:"discount_amount_minor_units"`
	TaxAmountMinorUnits      int64          `json:"tax_amount_minor_units"`
	LineTotalMinorUnits      int64          `json:"line_total_minor_units"`
	Currency                 string         `json:"currency"`
	SourceRef                string         `json:"source_ref"`
	PricingSnapshotJson      string         `json:"pricing_snapshot_json"`
	CreatedAt                string         `json:"created_at"`
}

func (q *Queries) CreateInvoiceLine(ctx context.Context, arg CreateInvoiceLineParams) error {
	_, err := q.db.ExecContext(ctx, createInvoiceLine,
		arg.ID,
		arg.InvoiceID,
		arg.TenantID,
		arg.BillableItemID,
		arg.Description,
		arg.Quantity,
		arg.UnitPriceMinorUnits,
		arg.DiscountAmountMinorUnits,
		arg.TaxAmountMinorUnits,
		arg.LineTotalMinorUnits,
		arg.Currency,
		arg.SourceRef,
		arg.PricingSnapshotJson,
		arg.CreatedAt,
	)
	return err
}

const deleteInvoiceLinesByInvoice = `-- name: DeleteInvoiceLinesByInvoice :exec
DELETE FROM invoice_lines
WHERE
  invoice_id = ?
`

func (q *Queries) DeleteInvoiceLinesByInvoice(ctx context.Context, invoiceID string) error {
	_, err := q.db.ExecContext(ctx, deleteInvoiceLinesByInvoice, invoiceID)
	return err
}

const upsertInvoice = `-- name: UpsertInvoice :exec
INSERT INTO
  invoices (
    id,
    tenant_id,
    customer_id,
    contract_id,
    external_id,
    invoice_number,
    period_start,
    period_end,
    issued_at,
    due_at,
    currency,
    total_amount_minor_units,
    status,
    source_system,
    created_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (tenant_id, source_system, external_id) DO UPDATE
SET
  customer_id = excluded.customer_id,
  contract_id = excluded.contract_id,
  invoice_number = excluded.invoice_number,
  period_start = excluded.period_start,
  period_end = excluded.period_end,
  issued_at = excluded.issued_at,
  due_at = excluded.due_at,
  currency = excluded.currency,
  total_amount_minor_units = excluded.total_amount_minor_units,
  status = excluded.status
`

type UpsertInvoiceParams struct {
	ID                    string         `json:"id"`
	TenantID              string         `json:"tenant_id"`
	CustomerID            string         `json:"customer_id"`
	ContractID            string         `json:"contract_id"`
	ExternalID            string         `json:"external_id"`
	InvoiceNumber         string         `json:"invoice_number"`
	PeriodStart           string         `json:"period_start"`
	PeriodEnd             string         `json:"period_end"`
	IssuedAt              string         `json:"issued_at"`
	DueAt                 sql.NullString `json:"due_at"`
	Currency              string         `json:"currency"`
	TotalAmountMinorUnits int64          `json:"total_amount_minor_units"`
	Status                string         `json:"status"`
	SourceSystem          string         `json:"source_system"`
	CreatedAt             string         `json:"created_at"`
}

func (q *Queries) UpsertInvoice(ctx context.Context, arg UpsertInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, upsertInvoice,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.ContractID,
		arg.ExternalID,
		arg.InvoiceNumber,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.IssuedAt,
		arg.DueAt,
		arg.Currency,
		arg.TotalAmountMinorUnits,
		arg.Status,
		arg.SourceSystem,
		arg.CreatedAt,
	)
	return err
}

const upsertUsageRecord = `-- name: UpsertUsageRecord :exec
INSERT INTO
  usage_records (
    id,
    tenant_id,
    customer_id,
    contract_id,
    billable_item_id,
    external_id,
    usage_time,
    quantity,
    unit,
    source_system,
    trace_id,
    metadata_json,
    created_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (tenant_id, source_system, external_id) DO UPDATE
SET
  customer_id = excluded.customer_id,
  contract_id = excluded.contract_id,
  billable_item_id = excluded.billable_item_id,
  usage_time = excluded.usage_time,
  quantity = excluded.quantity,
  unit = excluded.unit,
  trace_id = excluded.trace_id,
  metadata_json = excluded.metadata_json
`

type UpsertUsageRecordParams struct {
	ID             string `json:"id"`
	TenantID       string `json:"tenant_id"`
	CustomerID     string `json:"customer_id"`
	ContractID     string `json:"contract_id"`
	BillableItemID string `json:"billable_item_id"`
	ExternalID     string `json:"external_id"`
	UsageTime      string `json:"usage_time"`
	Quantity       int64  `json:"quantity"`
	Unit           string `json:"unit"`
	SourceSystem   string `json:"source_system"`
	TraceID        string `json:"trace_id"`
	MetadataJson   string `json:"metadata_json"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) UpsertUsageRecord(ctx context.Context, arg UpsertUsageRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertUsageRecord,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.ContractID,
		arg.BillableItemID,
		arg.ExternalID,
		arg.UsageTime,
		arg.Quantity,
		arg.Unit,
		arg.SourceSystem,
		arg.TraceID,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	return err
}
