// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"database/sql"
)

type ActualRevenueEntry struct {
	ID                     string `json:"id"`
	TenantID               string `json:"tenant_id"`
	CustomerID             string `json:"customer_id"`
	ContractID             string `json:"contract_id"`
	BillableItemID         string `json:"billable_item_id"`
	PeriodStart            string `json:"period_start"`
	PeriodEnd              string `json:"period_end"`
	ActualAmountMinorUnits int64  `json:"actual_amount_minor_units"`
	Currency               string `json:"currency"`
	RecognizedFrom         string `json:"recognized_from"`
	RecognizedAt           string `json:"recognized_at"`
	TraceID                string `json:"trace_id"`
}

type Adjustment struct {
	ID               string         `json:"id"`
	TenantID         string         `json:"tenant_id"`
	CustomerID       string         `json:"customer_id"`
	ContractID       sql.NullString `json:"contract_id"`
	AdjustmentType   string         `json:"adjustment_type"`
	AmountMinorUnits int64          `json:"amount_minor_units"`
	Currency         string         `json:"currency"`
	ReasonCode       string         `json:"reason_code"`
	CreatedAt        string         `json:"created_at"`
	SourceRef        string         `json:"source_ref"`
	MetadataJson     string         `json:"metadata_json"`
}

type BillableItem struct {
	ID          string `json:"id"`
	TenantID    string `json:"tenant_id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	Unit        string `json:"unit"`
	PricingMode string `json:"pricing_mode"`
	Status      string `json:"status"`
	CreatedAt   string `json:"created_at"`
}

type CaseStatusHistory struct {
	ID         string `json:"id"`
	CaseID     string `json:"case_id"`
	FromStatus string `json:"from_status"`
	ToStatus   string `json:"to_status"`
	ChangedAt  string `json:"changed_at"`
	ChangedBy  string `json:"changed_by"`
	ReasonCode string `json:"reason_code"`
	Comment    string `json:"comment"`
}

type Contract struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	CustomerID   string         `json:"customer_id"`
	ExternalID   sql.NullString `json:"external_id"`
	Status       string         `json:"status"`
	StartDate    string         `json:"start_date"`
	EndDate      sql.NullString `json:"end_date"`
	Currency     string         `json:"currency"`
	Version      int64          `json:"version"`
	BillingModel string         `json:"billing_model"`
	SignedAt     sql.NullString `json:"signed_at"`
	MetadataJson string         `json:"metadata_json"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type ContractTerm struct {
	ID             string         `json:"id"`
	TenantID       string         `json:"tenant_id"`
	ContractID     string         `json:"contract_id"`
	TermType       string         `json:"term_type"`
	EffectiveFrom  string         `json:"effective_from"`
	EffectiveTo    sql.NullString `json:"effective_to"`
	Priority       int64          `json:"priority"`
	ExpressionJson string         `json:"expression_json"`
	SourceRef      string         `json:"source_ref"`
	CreatedAt      string         `json:"created_at"`
}

type CustomerAccount struct {
	ID               string         `json:"id"`
	TenantID         string         `json:"tenant_id"`
	ExternalID       sql.NullString `json:"external_id"`
	Name             string         `json:"name"`
	Segment          string         `json:"segment"`
	BillingProfileID sql.NullString `json:"billing_profile_id"`
	Status           string         `json:"status"`
	MetadataJson     string         `json:"metadata_json"`
	CreatedAt        string         `json:"created_at"`
}

type ExpectedRevenueEntry struct {
	ID                       string `json:"id"`
	TenantID                 string `json:"tenant_id"`
	CustomerID               string `json:"customer_id"`
	ContractID               string `json:"contract_id"`
	BillableItemID           string `json:"billable_item_id"`
	PeriodStart              string `json:"period_start"`
	PeriodEnd                string `json:"period_end"`
	ExpectedAmountMinorUnits int64  `json:"expected_amount_minor_units"`
	Currency                 string `json:"currency"`
	CalculationBasisJson     string `json:"calculation_basis_json"`
	CalculatedAt             string `json:"calculated_at"`
	Version                  int64  `json:"version"`
	TraceID                  string `json:"trace_id"`
}

type Invoice struct {
	ID                    string         `json:"id"`
	TenantID              string         `json:"tenant_id"`
	CustomerID            string         `json:"customer_id"`
	ContractID            string         `json:"contract_id"`
	ExternalID            string         `json:"external_id"`
	InvoiceNumber         string         `json:"invoice_number"`
	PeriodStart           string         `json:"period_start"`
	PeriodEnd             string         `json:"period_end"`
	IssuedAt              string         `json:"issued_at"`
	DueAt                 sql.NullString `json:"due_at"`
	Currency              string         `json:"currency"`
	TotalAmountMinorUnits int64          `json:"total_amount_minor_units"`
	Status                string         `json:"status"`
	SourceSystem          string         `json:"source_system"`
	CreatedAt             string         `json:"created_at"`
}

type InvoiceLine struct {
	ID                       string         `json:"id"`
	InvoiceID                string         `json:"invoice_id"`
	TenantID                 string         `json:"tenant_id"`
	BillableItemID           sql.NullString `json:"billable_item_id"`
	Description              string         `json:"description"`
	Quantity                 int64          `json:"quantity"`
	UnitPriceMinorUnits      int64          `json:"unit_price_minor_units"`
	DiscountAmountMinorUnits int64          `json:"discount_amount_minor_units"`
	TaxAmountMinorUnits      int64          `json:"tax_amount_minor_units"`
	LineTotalMinorUnits      int64          `json:"line_total_minor_units"`
	Currency                 string         `json:"currency"`
	SourceRef                string         `json:"source_ref"`
	PricingSnapshotJson      string         `json:"pricing_snapshot_json"`
	CreatedAt                string         `json:"created_at"`
}

type LeakageCase struct {
	ID                         string `json:"id"`
	TenantID                   string `json:"tenant_id"`
	CustomerID                 string `json:"customer_id"`
	ContractID                 string `json:"contract_id"`
	CaseType                   string `json:"case_type"`
	Severity                   string `json:"severity"`
	Status                     string `json:"status"`
	DetectedAt                 string `json:"detected_at"`
	PeriodStart                string `json:"period_start"`
	PeriodEnd                  string `json:"period_end"`
	ExpectedAmountMinorUnits   int64  `json:"expected_amount_minor_units"`
	ActualAmountMinorUnits     int64  `json:"actual_amount_minor_units"`
	LeakageAmountMinorUnits    int64  `json:"leakage_amount_minor_units"`
	Currency                   string `json:"currency"`
	ConfidenceScoreBasisPoints int64  `json:"confidence_score_basis_points"`
	RootCauseCategory          string `json:"root_cause_category"`
	Assignee                   string `json:"assignee"`
	TraceID                    string `json:"trace_id"`
}

type LeakageEvidence struct {
	ID           string `json:"id"`
	CaseID       string `json:"case_id"`
	EvidenceType string `json:"evidence_type"`
	EntityType   string `json:"entity_type"`
	EntityID     string `json:"entity_id"`
	PayloadJson  string `json:"payload_json"`
	CreatedAt    string `json:"created_at"`
}

type OutboxEvent struct {
	ID            string         `json:"id"`
	TenantID      sql.NullString `json:"tenant_id"`
	AggregateType string         `json:"aggregate_type"`
	AggregateID   string         `json:"aggregate_id"`
	Topic         string         `json:"topic"`
	MessageKey    string         `json:"message_key"`
	PayloadJson   string         `json:"payload_json"`
	HeadersJson   string         `json:"headers_json"`
	Status        string         `json:"status"`
	OccurredAt    string         `json:"occurred_at"`
	PublishedAt   sql.NullString `json:"published_at"`
}

type Payment struct {
	ID               string `json:"id"`
	TenantID         string `json:"tenant_id"`
	CustomerID       string `json:"customer_id"`
	ExternalID       string `json:"external_id"`
	AmountMinorUnits int64  `json:"amount_minor_units"`
	Currency         string `json:"currency"`
	ReceivedAt       string `json:"received_at"`
	Status           string `json:"status"`
	AllocationStatus string `json:"allocation_status"`
	SourceSystem     string `json:"source_system"`
	CreatedAt        string `json:"created_at"`
}

type PaymentAllocation struct {
	ID                        string `json:"id"`
	TenantID                  string `json:"tenant_id"`
	PaymentID                 string `json:"payment_id"`
	InvoiceID                 string `json:"invoice_id"`
	AllocatedAmountMinorUnits int64  `json:"allocated_amount_minor_units"`
	Currency                  string `json:"currency"`
	AllocatedAt               string `json:"allocated_at"`
}

type ReconciliationRun struct {
	ID                      string         `json:"id"`
	TenantID                string         `json:"tenant_id"`
	ContractID              string         `json:"contract_id"`
	PeriodStart             string         `json:"period_start"`
	PeriodEnd               string         `json:"period_end"`
	Status                  string         `json:"status"`
	StartedAt               string         `json:"started_at"`
	CompletedAt             sql.NullString `json:"completed_at"`
	ExpectedCount           int64          `json:"expected_count"`
	ActualCount             int64          `json:"actual_count"`
	DiffCount               int64          `json:"diff_count"`
	CaseCount               int64          `json:"case_count"`
	LeakageAmountMinorUnits int64          `json:"leakage_amount_minor_units"`
	Currency                string         `json:"currency"`
	TraceID                 string         `json:"trace_id"`
}

type RootCause struct {
	ID                         string `json:"id"`
	CaseID                     string `json:"case_id"`
	Category                   string `json:"category"`
	Subcategory                string `json:"subcategory"`
	Description                string `json:"description"`
	ConfidenceScoreBasisPoints int64  `json:"confidence_score_basis_points"`
	DerivedBy                  string `json:"derived_by"`
	CreatedAt                  string `json:"created_at"`
}

type SlaEvent struct {
	ID          string         `json:"id"`
	TenantID    string         `json:"tenant_id"`
	CustomerID  string         `json:"customer_id"`
	ContractID  string         `json:"contract_id"`
	EventType   string         `json:"event_type"`
	StartedAt   string         `json:"started_at"`
	EndedAt     sql.NullString `json:"ended_at"`
	Severity    string         `json:"severity"`
	ImpactScope string         `json:"impact_scope"`
	SourceRef   string         `json:"source_ref"`
	CreatedAt   string         `json:"created_at"`
}

type Tenant struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Industry     string `json:"industry"`
	Currency     string `json:"currency"`
	Timezone     string `json:"timezone"`
	SettingsJson string `json:"settings_json"`
	CreatedAt    string `json:"created_at"`
}

type UsageRecord struct {
	ID             string `json:"id"`
	TenantID       string `json:"tenant_id"`
	CustomerID     string `json:"customer_id"`
	ContractID     string `json:"contract_id"`
	BillableItemID string `json:"billable_item_id"`
	ExternalID     string `json:"external_id"`
	UsageTime      string `json:"usage_time"`
	Quantity       int64  `json:"quantity"`
	Unit           string `json:"unit"`
	SourceSystem   string `json:"source_system"`
	TraceID        string `json:"trace_id"`
	MetadataJson   string `json:"metadata_json"`
	CreatedAt      string `json:"created_at"`
}
