// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createInboxEvent = `-- name: CreateInboxEvent :exec
INSERT OR IGNORE INTO inbox_events (
    event_id,
    handler,
    topic,
    source_key,
    processed_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type CreateInboxEventParams struct {
	EventID     string `json:"event_id"`
	Handler     string `json:"handler"`
	Topic       string `json:"topic"`
	SourceKey   string `json:"source_key"`
	ProcessedAt string `json:"processed_at"`
}

func (q *Queries) CreateInboxEvent(ctx context.Context, arg CreateInboxEventParams) error {
	_, err := q.db.ExecContext(ctx, createInboxEvent,
		arg.EventID,
		arg.Handler,
		arg.Topic,
		arg.SourceKey,
		arg.ProcessedAt,
	)
	return err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (
    id,
    topic,
    event_type,
    tenant_id,
    contract_id,
    partition_key,
    payload_json,
    headers_json,
    status,
    attempts,
    last_error,
    available_at,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    0,
    '',
    ?10,
    ?11
)
`

type CreateOutboxEventParams struct {
	ID           string         `json:"id"`
	Topic        string         `json:"topic"`
	EventType    string         `json:"event_type"`
	TenantID     string         `json:"tenant_id"`
	ContractID   sql.NullString `json:"contract_id"`
	PartitionKey string         `json:"partition_key"`
	PayloadJson  string         `json:"payload_json"`
	HeadersJson  string         `json:"headers_json"`
	Status       string         `json:"status"`
	AvailableAt  string         `json:"available_at"`
	CreatedAt    string         `json:"created_at"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.ExecContext(ctx, createOutboxEvent,
		arg.ID,
		arg.Topic,
		arg.EventType,
		arg.TenantID,
		arg.ContractID,
		arg.PartitionKey,
		arg.PayloadJson,
		arg.HeadersJson,
		arg.Status,
		arg.AvailableAt,
		arg.CreatedAt,
	)
	return err
}

const getInboxEvent = `-- name: GetInboxEvent :one
SELECT
    event_id,
    handler,
    topic,
    source_key,
    processed_at
FROM inbox_events
WHERE event_id = ?1
  AND handler = ?2
`

type GetInboxEventParams struct {
	EventID string `json:"event_id"`
	Handler string `json:"handler"`
}

func (q *Queries) GetInboxEvent(ctx context.Context, arg GetInboxEventParams) (InboxEvent, error) {
	row := q.db.QueryRowContext(ctx, getInboxEvent, arg.EventID, arg.Handler)
	var i InboxEvent
	err := row.Scan(
		&i.EventID,
		&i.Handler,
		&i.Topic,
		&i.SourceKey,
		&i.ProcessedAt,
	)
	return i, err
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT
    id,
    topic,
    event_type,
    tenant_id,
    contract_id,
    partition_key,
    payload_json,
    headers_json,
    status,
    attempts,
    last_error,
    available_at,
    created_at,
    published_at
FROM outbox_events
WHERE status IN ('pending', 'failed')
  AND available_at <= ?1
ORDER BY created_at ASC
LIMIT ?2
`

type ListPendingOutboxEventsParams struct {
	AvailableAt string `json:"available_at"`
	LimitCount  int64  `json:"limit_count"`
}

func (q *Queries) ListPendingOutboxEvents(ctx context.Context, arg ListPendingOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOutboxEvents, arg.AvailableAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.EventType,
			&i.TenantID,
			&i.ContractID,
			&i.PartitionKey,
			&i.PayloadJson,
			&i.HeadersJson,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.AvailableAt,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET
    status = 'failed',
    attempts = attempts + 1,
    last_error = ?1,
    available_at = ?2
WHERE id = ?3
`

type MarkOutboxEventFailedParams struct {
	LastError   string `json:"last_error"`
	AvailableAt string `json:"available_at"`
	ID          string `json:"id"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxEventFailed, arg.LastError, arg.AvailableAt, arg.ID)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET
    status = 'published',
    published_at = ?1,
    last_error = ''
WHERE id = ?2
`

type MarkOutboxEventPublishedParams struct {
	PublishedAt sql.NullString `json:"published_at"`
	ID          string         `json:"id"`
}

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, arg MarkOutboxEventPublishedParams) error {
	_, err := q.db.ExecContext(ctx, markOutboxEventPublished, arg.PublishedAt, arg.ID)
	return err
}
