// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: reconciliation.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const completeReconciliationRun = `-- name: CompleteReconciliationRun :exec
UPDATE reconciliation_runs
SET
    status = ?1,
    completed_at = ?2,
    expected_count = ?3,
    actual_count = ?4,
    diff_count = ?5,
    case_count = ?6,
    leakage_amount_minor_units = ?7
WHERE id = ?8
`

type CompleteReconciliationRunParams struct {
	Status                  string         `json:"status"`
	CompletedAt             sql.NullString `json:"completed_at"`
	ExpectedCount           int64          `json:"expected_count"`
	ActualCount             int64          `json:"actual_count"`
	DiffCount               int64          `json:"diff_count"`
	CaseCount               int64          `json:"case_count"`
	LeakageAmountMinorUnits int64          `json:"leakage_amount_minor_units"`
	ID                      string         `json:"id"`
}

func (q *Queries) CompleteReconciliationRun(ctx context.Context, arg CompleteReconciliationRunParams) error {
	_, err := q.db.ExecContext(ctx, completeReconciliationRun,
		arg.Status,
		arg.CompletedAt,
		arg.ExpectedCount,
		arg.ActualCount,
		arg.DiffCount,
		arg.CaseCount,
		arg.LeakageAmountMinorUnits,
		arg.ID,
	)
	return err
}

const createLeakageCase = `-- name: CreateLeakageCase :exec
INSERT INTO leakage_cases (
    id,
    tenant_id,
    customer_id,
    contract_id,
    case_type,
    severity,
    status,
    detected_at,
    period_start,
    period_end,
    expected_amount_minor_units,
    actual_amount_minor_units,
    leakage_amount_minor_units,
    currency,
    confidence_score_basis_points,
    root_cause_category,
    assignee,
    trace_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16,
    ?17,
    ?18
)
`

type CreateLeakageCaseParams struct {
	ID                         string `json:"id"`
	TenantID                   string `json:"tenant_id"`
	CustomerID                 string `json:"customer_id"`
	ContractID                 string `json:"contract_id"`
	CaseType                   string `json:"case_type"`
	Severity                   string `json:"severity"`
	Status                     string `json:"status"`
	DetectedAt                 string `json:"detected_at"`
	PeriodStart                string `json:"period_start"`
	PeriodEnd                  string `json:"period_end"`
	ExpectedAmountMinorUnits   int64  `json:"expected_amount_minor_units"`
	ActualAmountMinorUnits     int64  `json:"actual_amount_minor_units"`
	LeakageAmountMinorUnits    int64  `json:"leakage_amount_minor_units"`
	Currency                   string `json:"currency"`
	ConfidenceScoreBasisPoints int64  `json:"confidence_score_basis_points"`
	RootCauseCategory          string `json:"root_cause_category"`
	Assignee                   string `json:"assignee"`
	TraceID                    string `json:"trace_id"`
}

func (q *Queries) CreateLeakageCase(ctx context.Context, arg CreateLeakageCaseParams) error {
	_, err := q.db.ExecContext(ctx, createLeakageCase,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.ContractID,
		arg.CaseType,
		arg.Severity,
		arg.Status,
		arg.DetectedAt,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.ExpectedAmountMinorUnits,
		arg.ActualAmountMinorUnits,
		arg.LeakageAmountMinorUnits,
		arg.Currency,
		arg.ConfidenceScoreBasisPoints,
		arg.RootCauseCategory,
		arg.Assignee,
		arg.TraceID,
	)
	return err
}

const createLeakageEvidence = `-- name: CreateLeakageEvidence :exec
INSERT INTO leakage_evidence (
    id,
    case_id,
    evidence_type,
    entity_type,
    entity_id,
    payload_json,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
`

type CreateLeakageEvidenceParams struct {
	ID           string `json:"id"`
	CaseID       string `json:"case_id"`
	EvidenceType string `json:"evidence_type"`
	EntityType   string `json:"entity_type"`
	EntityID     string `json:"entity_id"`
	PayloadJson  string `json:"payload_json"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) CreateLeakageEvidence(ctx context.Context, arg CreateLeakageEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, createLeakageEvidence,
		arg.ID,
		arg.CaseID,
		arg.EvidenceType,
		arg.EntityType,
		arg.EntityID,
		arg.PayloadJson,
		arg.CreatedAt,
	)
	return err
}

const createReconciliationRun = `-- name: CreateReconciliationRun :exec
INSERT INTO reconciliation_runs (
    id,
    tenant_id,
    contract_id,
    period_start,
    period_end,
    status,
    started_at,
    expected_count,
    actual_count,
    diff_count,
    case_count,
    leakage_amount_minor_units,
    currency,
    trace_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14
)
`

type CreateReconciliationRunParams struct {
	ID                      string `json:"id"`
	TenantID                string `json:"tenant_id"`
	ContractID              string `json:"contract_id"`
	PeriodStart             string `json:"period_start"`
	PeriodEnd               string `json:"period_end"`
	Status                  string `json:"status"`
	StartedAt               string `json:"started_at"`
	ExpectedCount           int64  `json:"expected_count"`
	ActualCount             int64  `json:"actual_count"`
	DiffCount               int64  `json:"diff_count"`
	CaseCount               int64  `json:"case_count"`
	LeakageAmountMinorUnits int64  `json:"leakage_amount_minor_units"`
	Currency                string `json:"currency"`
	TraceID                 string `json:"trace_id"`
}

func (q *Queries) CreateReconciliationRun(ctx context.Context, arg CreateReconciliationRunParams) error {
	_, err := q.db.ExecContext(ctx, createReconciliationRun,
		arg.ID,
		arg.TenantID,
		arg.ContractID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Status,
		arg.StartedAt,
		arg.ExpectedCount,
		arg.ActualCount,
		arg.DiffCount,
		arg.CaseCount,
		arg.LeakageAmountMinorUnits,
		arg.Currency,
		arg.TraceID,
	)
	return err
}

const listActualRevenueByContractPeriod = `-- name: ListActualRevenueByContractPeriod :many
SELECT
    id,
    tenant_id,
    customer_id,
    contract_id,
    billable_item_id,
    period_start,
    period_end,
    actual_amount_minor_units,
    currency,
    recognized_from,
    recognized_at,
    trace_id
FROM actual_revenue_entries
WHERE tenant_id = ?1
  AND contract_id = ?2
  AND period_start >= ?3
  AND period_end <= ?4
ORDER BY customer_id, billable_item_id, period_start, period_end, recognized_at
`

type ListActualRevenueByContractPeriodParams struct {
	TenantID    string `json:"tenant_id"`
	ContractID  string `json:"contract_id"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

func (q *Queries) ListActualRevenueByContractPeriod(ctx context.Context, arg ListActualRevenueByContractPeriodParams) ([]ActualRevenueEntry, error) {
	rows, err := q.db.QueryContext(ctx, listActualRevenueByContractPeriod,
		arg.TenantID,
		arg.ContractID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActualRevenueEntry{}
	for rows.Next() {
		var i ActualRevenueEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ContractID,
			&i.BillableItemID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.ActualAmountMinorUnits,
			&i.Currency,
			&i.RecognizedFrom,
			&i.RecognizedAt,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpectedRevenueByContractPeriod = `-- name: ListExpectedRevenueByContractPeriod :many
SELECT
    id,
    tenant_id,
    customer_id,
    contract_id,
    billable_item_id,
    period_start,
    period_end,
    expected_amount_minor_units,
    currency,
    calculation_basis_json,
    calculated_at,
    version,
    trace_id
FROM expected_revenue_entries
WHERE tenant_id = ?1
  AND contract_id = ?2
  AND period_start >= ?3
  AND period_end <= ?4
ORDER BY customer_id, billable_item_id, period_start, period_end, calculated_at
`

type ListExpectedRevenueByContractPeriodParams struct {
	TenantID    string `json:"tenant_id"`
	ContractID  string `json:"contract_id"`
	PeriodStart string `json:"period_start"`
	PeriodEnd   string `json:"period_end"`
}

func (q *Queries) ListExpectedRevenueByContractPeriod(ctx context.Context, arg ListExpectedRevenueByContractPeriodParams) ([]ExpectedRevenueEntry, error) {
	rows, err := q.db.QueryContext(ctx, listExpectedRevenueByContractPeriod,
		arg.TenantID,
		arg.ContractID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpectedRevenueEntry{}
	for rows.Next() {
		var i ExpectedRevenueEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ContractID,
			&i.BillableItemID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.ExpectedAmountMinorUnits,
			&i.Currency,
			&i.CalculationBasisJson,
			&i.CalculatedAt,
			&i.Version,
			&i.TraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
