// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: revenue.sql

package sqlitedb

import (
	"context"
)

const createActualRevenueEntry = `-- name: CreateActualRevenueEntry :exec
INSERT INTO actual_revenue_entries (
    id,
    tenant_id,
    customer_id,
    contract_id,
    billable_item_id,
    period_start,
    period_end,
    actual_amount_minor_units,
    currency,
    recognized_from,
    recognized_at,
    trace_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
)
`

type CreateActualRevenueEntryParams struct {
	ID                     string `json:"id"`
	TenantID               string `json:"tenant_id"`
	CustomerID             string `json:"customer_id"`
	ContractID             string `json:"contract_id"`
	BillableItemID         string `json:"billable_item_id"`
	PeriodStart            string `json:"period_start"`
	PeriodEnd              string `json:"period_end"`
	ActualAmountMinorUnits int64  `json:"actual_amount_minor_units"`
	Currency               string `json:"currency"`
	RecognizedFrom         string `json:"recognized_from"`
	RecognizedAt           string `json:"recognized_at"`
	TraceID                string `json:"trace_id"`
}

func (q *Queries) CreateActualRevenueEntry(ctx context.Context, arg CreateActualRevenueEntryParams) error {
	_, err := q.db.ExecContext(ctx, createActualRevenueEntry,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.ContractID,
		arg.BillableItemID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.ActualAmountMinorUnits,
		arg.Currency,
		arg.RecognizedFrom,
		arg.RecognizedAt,
		arg.TraceID,
	)
	return err
}

const createExpectedRevenueEntry = `-- name: CreateExpectedRevenueEntry :exec
INSERT INTO expected_revenue_entries (
    id,
    tenant_id,
    customer_id,
    contract_id,
    billable_item_id,
    period_start,
    period_end,
    expected_amount_minor_units,
    currency,
    calculation_basis_json,
    calculated_at,
    version,
    trace_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13
)
`

type CreateExpectedRevenueEntryParams struct {
	ID                       string `json:"id"`
	TenantID                 string `json:"tenant_id"`
	CustomerID               string `json:"customer_id"`
	ContractID               string `json:"contract_id"`
	BillableItemID           string `json:"billable_item_id"`
	PeriodStart              string `json:"period_start"`
	PeriodEnd                string `json:"period_end"`
	ExpectedAmountMinorUnits int64  `json:"expected_amount_minor_units"`
	Currency                 string `json:"currency"`
	CalculationBasisJson     string `json:"calculation_basis_json"`
	CalculatedAt             string `json:"calculated_at"`
	Version                  int64  `json:"version"`
	TraceID                  string `json:"trace_id"`
}

func (q *Queries) CreateExpectedRevenueEntry(ctx context.Context, arg CreateExpectedRevenueEntryParams) error {
	_, err := q.db.ExecContext(ctx, createExpectedRevenueEntry,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.ContractID,
		arg.BillableItemID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.ExpectedAmountMinorUnits,
		arg.Currency,
		arg.CalculationBasisJson,
		arg.CalculatedAt,
		arg.Version,
		arg.TraceID,
	)
	return err
}
